### ISSUE TITLE
Docs badge failing; recent changes missing from readthedocs

### ISSUE THREAD

**Issue by rikvl** [mhvk/screens#64]
@mhvk - I just noticed that the "docs badge" in `README.rst` says "failing", while the tox tests all passed.

Also, some documentation updates that were recently merged (like the addition of `error_analysis.rst`) don't show up on readthedocs.

I don't understand what's going on here, but locally, I had to remove some leftover files in `docs/api` after we renamed `secspec.py` to `conjspec.py` to make the docs build cleanly.

**Comment by mhvk** [comment]
Well, that took rather more effort than I thought! Turns out it was all about versions. The trickiest part was that the python version in `.readthedocs.yml` was too old to use astropy 5.0. Anyway, looks like it is fixed now.

Also, I now turned on readthedocs builds on pull requests, so we can be warned ahead of time.
